#!/bin/env bash
##############################################################################
#                                                                            #
# Copyright 2025 Nils Bosbach                                                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License");            #
# you may not use this file except in compliance with the License.           #
# You may obtain a copy of the License at                                    #
#                                                                            #
#     http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#                                                                            #
##############################################################################

set -e
# Get directory of script itself
SOURCE="${BASH_SOURCE[0]}"
# resolve $SOURCE until the file is no longer a symlink
while [ -h "$SOURCE" ]; do
        DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
        SOURCE="$(readlink "$SOURCE")"
        # if $SOURCE was a relative symlink, we need to resolve it relative to the
        # path where the symlink file was located
        [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

LINUX_CONFIG_FILE="${DIR}/files/avp64_linux_kernel.config"
BUILDROOT_DIR="${DIR}/buildroot"
LINUX_DIR="${BUILDROOT_DIR}/output/build/linux-6.5.6"

if [ ! -d "${LINUX_DIR}" ]; then
    pushd "${BUILDROOT_DIR}" > /dev/null
    make linux-menuconfig
    popd > /dev/null
fi;

cp "${LINUX_CONFIG_FILE}" "${LINUX_DIR}/.config"

pushd "${LINUX_DIR}" > /dev/null
make menuconfig ARCH=arm64
popd > /dev/null

cp "${LINUX_DIR}/.config" "${LINUX_CONFIG_FILE}"
