#!/bin/env bash

set -e
# Get directory of script itself
SOURCE="${BASH_SOURCE[0]}"
# resolve $SOURCE until the file is no longer a symlink
while [ -h "$SOURCE" ]; do
        DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
        SOURCE="$(readlink "$SOURCE")"
        # if $SOURCE was a relative symlink, we need to resolve it relative to the
        # path where the symlink file was located
        [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

BUILDROOT_CONFIG_FILE="${DIR}/files/avp64-linux-defconfig"
BUILDROOT_DIR="${DIR}/buildroot"

cp "${BUILDROOT_CONFIG_FILE}" "${BUILDROOT_DIR}/.config"

pushd "${BUILDROOT_DIR}" > /dev/null
make menuconfig
popd > /dev/null

cp "${BUILDROOT_DIR}/.config" "${BUILDROOT_CONFIG_FILE}"
